name: Deploy Recommender Engine to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./RecommenderEngine
        file: ./RecommenderEngine/Dockerfile
        push: true
        tags: dfanso/recommender-engine:latest
        build-args: |
          MONGODB_CONNECTION_STRING=${{ secrets.MONGO_URI }}

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          docker pull dfanso/recommender-engine:latest
          docker stop recommender-engine || true
          docker rm recommender-engine || true
          docker run -d --name recommender-engine -p 4001:8000 dfanso/recommender-engine:latest